server:
  port: 8000
spring:
  redis:
    host: 124.221.194.98
    port: 6380
    password: aurora123
    jedis:
      pool:
        time-between-eviction-runs: 30000
    timeout: 2000

  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true




