server:
  port: 8000
spring:
  application:
    name: auth-service
  profiles:
    include: jwt
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myzone?characterEncoding=UTF-8&useSSL=false
    hikari:
      max-lifetime: 50000

  redis:
    host: 124.221.194.98
    port: 6380
    password: aurora123
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      server-addr: 124.221.194.98:8848




logging:
  level:
    org.springframework.boot.autoconfigure: error

