

spring:
  cloud:
    nacos:
      server-addr: 124.221.194.98:8848
    gateway:
      discovery:
        locator:
          enabled: true #开启注册中心路由功能 根据id创建路由
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        - id: res-service
          uri: lb://res-service
          predicates:
            - Path=/res/**
          filters:
            - StripPrefix=1
