server:
  port: 8848

spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      server-addr: 124.221.194.98:8848
    gateway:
      discovery:
        locator:
          enabled: true #开启注册中心路由功能 根据id创建路由
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        - id: media-service
          uri: lb://media-service
          predicates:
            - Path=/media/**
#            - StripPrefix=1
  main:
    web-application-type: reactive
