server:
  port: 8001

spring:

  #  datasource:
  #    username: root
  #    password: 123456
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  #    url: jdbc:mysql://localhost:3306/myzone?characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true
  #    hikari:
  #      max-lifetime: 50000
  redis:
    host: 124.221.194.98
    port: 6380
    password: aurora123

